### ISSUE TITLE
Pass the exception code when an exception occurs

### ISSUE THREAD

**Issue by mnugter** [paknahad/jsonapi-bundle#15]
The exception listener passes null as exception code, it would be nice to pass the exception code of the thrown exception instead.

I'll create a PR for this change.

**Comment by mnugter** [comment]
The PR: #16

**Comment by paknahad** [comment]
I don't think so because this code will return as HTTP status code.
The status code must be 500 unless the exception was an HTTP exception.
[please check this line](https://github.com/paknahad/jsonapi-bundle/blob/9473e0f9da4e961a75f3050aa9223bb9c2fcb83a/src/EventSubscriber/JsonApiErrorHandlerEvent.php#L103)

another example: [yin-middelware](https://github.com/woohoolabs/yin-middleware/blob/23f6823a89442a29658f5b393b9acbc661c5d0c4/src/Middleware/JsonApiExceptionHandlerMiddleware.php#L80)

**Comment by mnugter** [comment]
You're right! It actually was passed as a status code. I deleted the PR and I'll close the issue.
